--------------------------------------------------------------
 --     Copyright (c) 2012-2023 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	D:/TD5.2.6/prj/ES8388/TD/al_ip/voice_change_ram.vhd
 -- Date	:	2025 11 03
 -- TD version	:	5.6.71036
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY voice_change_ram IS
PORT (
	doa	: OUT STD_LOGIC_VECTOR(31 DOWNTO 0);

	dia	: IN STD_LOGIC_VECTOR(31 DOWNTO 0);
	addra	: IN STD_LOGIC_VECTOR(9 DOWNTO 0);
	wea	: IN STD_LOGIC;
	cea	: IN STD_LOGIC;
	ocea	: IN STD_LOGIC;
	clka	: IN STD_LOGIC;
	rsta	: IN STD_LOGIC;

	dob	: OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
	dib	: IN STD_LOGIC_VECTOR(31 DOWNTO 0);
	addrb	: IN STD_LOGIC_VECTOR(9 DOWNTO 0);
	web	: IN STD_LOGIC;
	ceb	: IN STD_LOGIC;
	oceb	: IN STD_LOGIC;
	clkb	: IN STD_LOGIC;
	rstb	: IN STD_LOGIC
	);
END voice_change_ram;

ARCHITECTURE struct OF voice_change_ram IS

	BEGIN

	inst : EG_LOGIC_BRAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 32,
			DATA_WIDTH_B	=> 32,
			ADDR_WIDTH_A	=> 10,
			ADDR_WIDTH_b	=> 10,
			DATA_DEPTH_A	=> 1024,
			DATA_DEPTH_B	=> 1024,
			MODE		=> "DP",
			REGMODE_A	=> "OUTREG",
			REGMODE_B	=> "OUTREG",
			WRITEMODE_A	=> "NORMAL",
			WRITEMODE_B	=> "NORMAL",
			RESETMODE	=> "SYNC",
			IMPLEMENT		=> "9K",
			INIT_FILE		=> "NONE",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia	=> dia,
			dib	=> dib,
			addra	=> addra,
			addrb	=> addrb,
			cea	=> cea,
			ceb	=> ceb,
			ocea	=> ocea,
			oceb	=> oceb,
			clka	=> clka,
			clkb	=> clkb,
			wea	=> wea,
			web	=> web,
			bea	=> (others=>'0'),
			beb	=> (others=>'0'),
			rsta	=> rsta,
			rstb	=> rstb,
			doa	=> doa,
			dob	=> dob
		);

END struct;
